@localIp=http://127.0.0.1:7003


# 这个是本工程的测试 http 类, 使用 restclient 插件

###
# 用户查询
# @name queryUser
POST {{localIp}}/user/queryUser
Content-Type: application/json


###
# 用户查询
# @name seAll
POST {{localIp}}/user/seAll
Content-Type: application/json



###
# 用户添加
# @name batchAddUser
POST {{localIp}}/user/batchAddUser
Content-Type: application/json

[
    {
        "id": 777,
        "name": "masamiaoi777",
        "age": 77,
        "email": "00000"
    }
]



###
# 用户添加
# @name batchAddUserJsonArray
POST {{localIp}}/user/batchAddUserJsonArray
Content-Type: application/json

[
    {
        "id": 999,
        "name": "masamiaoi777",
        "age": 77,
        "email": "00000"
    }
]
